config: {}
dumplogs: false
headless: false
kube:
  configpath: ""
  context: ""
license: "FT7Y2AYBAEDUY2LDMVXHGZIB76HAAAIDAECEIYLUMEAQUAABAFJAD74QAAAQCUYB76IAAAAABL7Y6BIBAL7ZEAAAAD7AHK77RYA74AZ6PMRGK3LBNFWCEORCNRXXSZDQMFSGOZLUORAGO3LBNFWC4Y3PNURCYITVONSXESLEEI5CEVJSKYZU6VLLK54GORTOJM2VCZTBO4ZFUSKRGRZXEUTJJQRCYITBMNRWK43TKRXWWZLOEI5CEZLZJJUGER3DNFHWSSSTKV5ESMKONFEXGSLNORYFUQ2JGZEWYQLZKVEGY3LEIU4XAY2IIF4VEV2OLFLUMSRVMFMFUT3EGJ4EWYJRKZHFGRZQNFGEGSRQMVMEC2KPNFFEWVRRKFUWMUJOMV4UU2DCLBEWST3MONUVUVZRNBQVO53JLBJXO2K2JBFHKSLKN5UVERSNNFGEGSTMMVEEC2KPNJCTET2UKF3U42SFGVGXU23TJFWWY2DEINETMTKULE2U4RCBGJGVITL2J5JXO2LBLBHHUSLKN5UVKRCKKFSVOWRQKQZGY53DIRFEMWJRNBMVK3TMOBSGWNJTMJCXA4SWKUYUSYSTJFZUS3SKNRSUQQLJJ5UUS6KNIREXUTCUIV3UYVCBGFLEIQJQJ5VE2MKPNJGTKV3JJFZUS3SOGFMWSSJWJFWFK6KWNJHFAVSXORMGKR3EI5RGW4ZRKVLVU2DEPJFGCU2WIUYGGM2KKNQVK53JMZIS4Z2BLFZTS3KJPI4EKN3BONIXSWTRI5ITKWCIM5LG6TDFNNZG423GHFVWQNLIGBYUK6KMK54G4MTRIZTG2N2RJVXS2ZCQNZGU4SBWGFXDAURRFVPVKUJXOZFVU23FJN2W2OKYIRUUWM2FIZYTILJWOF2GUY3IM5VHC23FOFVE6MRWG5US2WKYNE2GYTTIJJHDORKIIVRHOTLOMNRVM6TNNB2GKWCVJREUWQ2YN4YUGMJQNRJFOMLXN52XI43IOBTDQTTYJ5MUIQ2FMZYXIUTNJZ2FGTTXGY3U2VRZGRYWIVLOMRWFI4CNIJMUSNKCJ5SDKR3FLFWTQVDOLEYDIY2NOU3WEZSROJBVESSRNNSWGNLKJBMXCR2INBGXMUCTNVCFQX3JOAWWUV3PNAYUQTTTIRCE2SLVJFRWSMLHON4WQQ3KJY4HORTDMJUGESDQHBSFSZ3QMRFEE4LYJU2DQNDNFVMWOY2JI5RUMVCLKJGGKRLTONJU6MDWIFIWG5CHHBNGWYKCNRGUOTCFOZJGWMRWOVZUMSLIOZ3GCTTXEIWCEZLENF2GS33OEI5CEUCSJ4RCYITON5SGK4ZCHIYTAMBMEJSW4ZBCHIYTMOJWGY2TGMZTGUYDCMZMEJQXA4C7NFSCEORCKAZFA6LGORHWS4DQGJCWGWCYKJ4WS5SOO5WEU22VJVEG2IT5AEYQFOQ2UY2FYYV2X2RGCZKCWFFFGDMJUEDJM5WRS34GYE3PKLONRKMQGT6UURFDMGSF26ABFJI5WULBR4ATCAV7C3NVF7GQ2GS26QANXWWWLAFIVMZGBMF3SU3GPGS6CMFPYHCRUPV3YYIERN2YCV6IFOEU4XNMVXJAA==="
logs:
  file: ""
manifests:
  dump: false
scripting:
  env: null
  source: ""
  watchscripts: true
tap:
  annotations: {}
  auth:
    approveddomains: []
    approvedemails: []
    enabled: false
  debug: false
  docker:
    imagepullpolicy: Always
    imagepullsecrets: null
    registry: docker.io/kubeshark
    tag: latest
  dryrun: false
  ignoretainted: false
  ingress:
    # certmanager: letsencrypt-prod
    classname: nginx
    controller: k8s.io/ingress-nginx
    enabled: true
    host: ks.auth.k3s.lan
    tls: 
      - secretName: kubeshark-general-tls
        hosts:
          - ks.auth.k3s.lan
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "false"
      cert-manager.io/cluster-issuer: selfsigned-issuer
  ipv6: true
  labels: {}
  namespaces: kubeshark
  nodeselectorterms:
    - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
  packetcapture: libpcap
  pcap: ""
  persistentstorage: false
  proxy:
    front:
      port: 8899
    host: 127.0.0.1
    hub:
      port: 8898
      srvport: 8898
    worker:
      srvport: 8897
  regex: .*
  release:
    name: kubeshark
    namespace: kubeshark
    repo: https://helm.kubeshark.co
  resources:
    hub:
      limits:
        cpu: 750m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 50Mi
    worker:
      limits:
        cpu: 750m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 50Mi
  servicemesh: true
  storageclass: standard
  storagelimit: 200Mi
  telemetry:
    enabled: true
  tls: true
