config: {}
dumplogs: false
headless: false
kube:
  configpath: ""
  context: ""
license: "FT7YKAYBAEDUY2LDMVXHGZIB76DAAAIDAECEIYLUMEAQUAABAFJAD74IAAAQCUYB76EAAAAABL7YOBIBAL7YUAAAAD7AHK77QYA74AZ6PMRGK3LBNFWCEORCNRXXSZDQMFSGOZLUORAGO3LBNFWC4Y3PNURCYITVONSXESLEEI5CEVJSKYZU6VLLK54GORTOJM2VCZTBO4ZFUSKRGRZXEUTJJQRCYITBMNRWK43TKRXWWZLOEI5CEZLZJJUGER3DNFHWSSSTKV5ESMKONFEXGSLNORYFUQ2JGZEWYQLZKVEGY3LEIU4XAY2IIF4VEV2OLFLUMSRVMFMFUT3EGJ4EWYJRKZHFGRZQNFGEGSRQMVMEC2KPNFFEWVRRKFUWMUJOMV4UU2DCLBEWST3MONUVUVZRNBQVO53JLBJXO2K2JBFHKSLKN5UVERSNNFGEGSTMMVEEC2KPNJCTET2UKF4E4RCFPJGVIY3TJFWWY2DEINETMTKULE2U4RCFGBGUIY3YJZ4XO2LBLBHHUSLKN5UVKRCKKFSVOWRQKQZGY53DIRFEMWJRNBMVK3TMOBSGWNJTMJCXA4SWKUYUSYSTJFZUS3SKNRSUQQLJJ5UUS6KNIREXUTCUIV3UYVCBGJLEIQLZJ5VE2NCPNJGTGV3JJFZUS3SOGFMWSSJWJFWFK6KWNJHFAVSXORMGKR3EI5RGW4ZRKVLVU2DEPJFGCU2WIUYGGM2KKNQVK53JMZIS4QSKO53EYSDJMNXWISCTG5BTI5ZUMRJHGTKHKBKG4OLMJVJWCOCIJRNG2UCQOMYWIYRRJ44WQOCXKFTWIUSEORPXSUKNGVRXMQ3SORJGOLLROZXHS4DMNBAUWQJUG5YGWTDRLI4TQZ3EKB2XOYZWMVGFM2S2PF5EU2JUJ5KEMOLLIFKUUN2PKFDVAVDHHFZDMUSELBJUOVSZNVIUESTJKBUFG3KFOZCUM3TVGMWUYT3ENZHE2ZSCGNGEU5BQOMYW4YSOORCVER2GKJLGGNLVKY2UMWSNOVYUSVZXNJMWMM3SOY4W2V3YMFWTI6C2LE2XOTDKJBGG4SSNNQZTM4TWKF3E45LZHBLW66CCI43HEQ3XGJYXG4ZWMRIVOSRRNNCDQWC2KN5EKNTYKZWFI6LDL52XEOCJGNXHMWRXK44TEVCXMFXDITCEORHU64BRJNAXI43ZJ5YEW2DDG4YHCRSUPJSGC6TBGJJTAV2GMFDVAZJVOR3F6TCTOVRHQSSZL5ZE4NKQNZYDQ53MNJVUUSTYNRJVMWRXOFXF66LXEIWCEZLENF2GS33OEI5CEUCSJ4RCYITON5SGK4ZCHIYTAMBMEJSW4ZBCHIYTMOJWGY2TGMZTGUYDCMZMEJQXA4C7NFSCEORCKAZFA6LGORHWS4DQGJCWGWCYKJ4WS5SOO5WEU22VJVEG2IT5AEYQEPU5T4RVQMPS5G74HPR6VQDIZYP2KFI7YILRKV5X2RLGZDKJ2X3CRIJUOJNUZ45RS7OX655D6RDJGEATCAWSP6BFILPXBOEZS2TZY24YKRYKXK3S3DGSBMWKEM66ZNBU2HDZ7U7TNXZLTM3HMHPG2FXDONFOJIQAA==="
logs:
  file: ""
manifests:
  dump: false
scripting:
  env: null
  source: ""
  watchscripts: true
tap:
  annotations: {}
  auth:
    approveddomains: []
    approvedemails: []
    enabled: false
  debug: false
  docker:
    imagepullpolicy: Always
    imagepullsecrets: null
    registry: docker.io/kubeshark
    tag: latest
  dryrun: false
  ignoretainted: false
  ingress:
    #certmanager: letsencrypt-prod
    classname: nginx
    controller: k8s.io/ingress-nginx
    enabled: true
    host: ks.auth.k3s.lan
    tls: 
      - secretName: ks-auth-secret
  ipv6: true
  labels: {}
  namespaces: []
  nodeselectorterms:
    - matchExpressions:
        - key: kubernetes.io/os
          operator: In
          values:
            - cp1
  packetcapture: libpcap
  pcap: ""
  persistentstorage: false
  proxy:
    front:
      port: 8899
    host: 0.0.0.0
    hub:
      port: 8898
      srvport: 8898
    worker:
      srvport: 8897
  regex: .*
  release:
    name: kubeshark
    namespace: default
    repo: https://helm.kubeshark.co
  resources:
    hub:
      limits:
        cpu: 750m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 50Mi
    worker:
      limits:
        cpu: 750m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 50Mi
  servicemesh: true
  storageclass: standard
  storagelimit: 200Mi
  telemetry:
    enabled: true
  tls: true
